doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Book:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/BookStore/Infrastructure/Storage/Doctrine/Entity'
                        prefix: 'App\BookStore\Infrastructure\Storage\Doctrine\Entity'
                        alias: App
