services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\BookStore\Domain\BookRepository:
        class: 'App\BookStore\Infrastructure\Storage\Doctrine\Repository\Book\BookRepository'

    App\BookStore\Infrastructure\Bus\CommandBus: ~
    App\BookStore\Infrastructure\Bus\QueryBus: ~

    command_handler:
        namespace: App\BookStore\Application\Write\
        resource: '%kernel.project_dir%/src/BookStore/Application/Write/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: command.bus }

    query_handler:
        namespace: App\BookStore\Application\Read\
        resource: '%kernel.project_dir%/src/BookStore/Application/Read/*Handler.php'
        autoconfigure: false
        tags:
            - { name: messenger.message_handler, bus: query.bus }

    controllers:
        namespace: App\BookStore\Infrastructure\UserInterface\Web\
        resource: '%kernel.project_dir%/src/BookStore/Infrastructure/UserInterface/Web/*Controller.php'
        public: true
        tags:
            - { name: controller.service_arguments }